
let htmlCard = '<a href="{URL}">'
    + '<div class="card bd-best-item bd-is-medium  is-free" > '
    + '<div class="card-image" >'
    + '<figure class="image is-4by3">'
    + '<img style="width:100%" src="{Image}" alt="Placeholder image">'
    + '</figure>'
    + ' </div>'
    + '<div class="card-content">'
    + '<div class="media">'
    + '<div class="media-content">'
    + '<p class="title is-4">{Title}</p>'
    + '</div>'
    + '</div>  '
    + ' <div class="content">'
    + '{Country}'
    + '</div>'
    + '</div>'
    + '</div>'
    + '</a>';
let htmlCleanFiltersResponsive = '<hr class="dropdown-divider">'
      +'<a href="#" class="dropdown-item" onclick="paintChannels(data.Channels)">'
       +' Todos los canales'
      +'</a>'
let htmlMenuItemResponsive = '<a href="#" class="dropdown-item" onclick="filterChannels({filters})">'
    + '{ItemMenu}</a>'
let htmlMenuLabelResponsive = '<p class="menu-label">'
    + '{LabelMenu}'
    + '</p> {ItemsMenu}'
let htmlCleanFilters = '<p class="menu-label" onclick="paintChannels(data.Channels)"><a>'
    + 'Todos los canales'
    + '</a></p>';
let htmlMenuItem = '<li onclick="filterChannels({filters})"><a>{ItemMenu}</a></li>';
let htmlMenuLabel = '<p class="menu-label">'
    + '{LabelMenu}'
    + '</p>'
    + '<ul class="menu-list">'
    + '{ItemsMenu}'
    + '</ul>';

let htmlDropDownTrigger = '<div class="dropdown-trigger">'
    + '<button class="button" aria-haspopup="true" aria-controls="dropdown-menu">'
    + '<span>Filters</span>'
    + '<span class="icon is-small">'
    + '<i class="fas fa-angle-down" aria-hidden="true"></i>'
    + '</span>'
    + '  </button>'
    + '</div>';
let htmlButtons  = `<btn class="button is-{Style} is-inverted" onclick="paintIframe('{URL}')">{Text}</btn>`
let htmlItemTitel = '<div class="bd-feature is-{Style}">'
+ '<div class="bd-feature-body">'
    + '<span class="icon is-medium">'
      + '<img src="{Image}"/>'
      + '</span>'
    + '<h2 class="bd-feature-title">{Name}</h2>'
    + '<h3 class="bd-feature-subtitle">{Country}</h3>'
  + '</div>'
  + '</div>'